[build]
  command = "bundle install && bundle exec jekyll build --source docs --destination public --config docs/_config.yml,docs/_config.netlify.yml"
  publish = "public"

[build.environment]
  RUBY_VERSION = "3.2.2"
